seat-bidding:
  reminders:
    schedule:
      enabled: false
    web-push:
      vapid-subject: mailto:development@localhost
      vapid-public-key: BJ7tFVi60Tw6Y0xchiuEZjd62SBdsK0_-zDEk3W-blZy0hB5UUUkbiq6BZxeN5529gkofV463kj-WAaBib5vxYY
      vapid-private-key: I4dqtEfeVxGFPO5i0TJugmklqM_g8uzIa-xwrgMMLok
  authentication:
    activation:
      code-pepper: "oE_Q-%ag@rBPf-kNZtFqEdUa6JOo4pYW"
    allowed-web-origins:
      - http://localhost:8080

quarkus:
  http:
    auth:
      session:
        encryption-key: "D_gmYlWh-PDWAU0WJ3fL4T^cHnQmu8-x"
  rest-csrf:
    token-signature-key: "KqjGxu3F3hC5SoMZfJsk7pw6@db3qub0"
    cookie-force-secure: false
  mailer:
    mock: true
    from: seats@localhost
    host: localhost
    port: 1025
    username: development
    password: development
  log:
    category:
      "de.gigaworks.seatbidding":
        level: DEBUG
      "quarkus-mailer":
        level: INFO